### PR TITLE
add ESM support

### LINKED ISSUE #13: export also as ESM module
We get the following waning in an Angular project using keychartm (for vis-timeline):

```
WARNING in node_modules/vis-timeline/esnext/esm/vis-timeline-graph2d.js depends on 'propagating-hammerjs'.
CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

It would be helpfull to also export a ESM module.

### PR DESCRIPTION
**Pull request by mojoaxel**
fixes #13

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Alexander, looks very neat!

The code looks good, though I haven't yet tested functionally.

I think it would be good to remove `./propagating.js` from the repo, since this is now generated from `./src/propagating.js`, what do you think?

**Comment by mojoaxel** [comment]
>I think it would be good to remove ./propagating.js from the repo, since this is now generated from ./src/propagating.js, what do you think?

I think we need to keep this file. It is till the package's [main entry](https://github.com/josdejong/propagating-hammerjs/blob/master/package.json#L5). Normally I would have moved it to a `dist` folder but I didn't want to introduce a breaking change.

**Comment by josdejong** [comment]
The file should only be removed from the repo, not from the published package, that should be ok, or not?

**Comment by mojoaxel** [comment]
> The file should only be removed from the repo, not from the published package, that should be ok, or not?

That's unusual but it makes sence in this case! I'll update the PR.

**Comment by josdejong** [comment]
Looks good @mojoaxel , thanks.

I think the git repo is for source code, and including generated bundles and builds pollutes the repo. It was necessary during the time that bower was popular, but now it is just as easy to keep the source separate from the package on npm. And having a dist folder with bundles in the repo easily gives conflicts when having pull requests each including their own slightly changed bundle.

I'll merge your PR now and write out the `*` under files and change the pre-commit to a prepublishOnly script (so we're sure it's build before publishing).

**Comment by mojoaxel** [comment]
Perfect!

**Comment by josdejong** [comment]
Published your PR now as `v1.5.0`. Thanks again 👍

**Pull request merged**
